python train.py \
        --cuda \
        --root /mnt/share/ssd2/dataset/ \
        -d coco \
        -v fcos_r50_fpn_1x \
        --lr 0.01 \
        --norm GN \
        --batch_size 8 \
        --img_size 800 \
        --wp_iter 500 \
        --accumulate 2
